networks:
  yacht:
    name: yacht-proxy

services:
  traefik:
    image: traefik:v2.6
    container_name: yacht-traefik
    command:
      - '--api.insecure=true'
      - '--providers.docker'
    networks:
      - yacht
    ports:
      - '127.0.0.1:80:80'
      - '127.0.0.1:8080:8080'
    labels:
      - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
